# Generated by Django 4.0.3 on 2022-04-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projec',
            new_name='Project',
        ),
    ]
